"""環境変数キー名の一元定義"""

# --- API Keys ---
API_KEYS = ("ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY",
            "CONTEXT7_API_KEY", "PYPI_API_KEY", "NPM_TOKEN")

# --- AWS ---
AWS_CONFIG_BASE64 = "AWS_CONFIG_BASE64"
AWS_PROFILE = "AWS_PROFILE"
AWS_ACCESS_KEY_ID = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "AWS_SECRET_ACCESS_KEY"
AWS_DEFAULT_REGION = "AWS_DEFAULT_REGION"
AWS_SSO_URL = "AWS_SSO_URL"
AWS_ALL_KEYS = (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,
                AWS_PROFILE, AWS_CONFIG_BASE64, AWS_SSO_URL)

# --- Devin ---
DEVIN_KEYS = ("DEVIN_API_KEY", "DEVIN_API_ORG_WIDE", "DEVIN_ORG_ID",
              "DEVIN_SERVICE_USER", "DEVIN_SERVICE_ADMIN")

# --- Git ---
GIT_USER_NAME = "GIT_USER_NAME"
GIT_USER_EMAIL = "GIT_USER_EMAIL"
GIT_CREDENTIAL_HELPER = "GIT_CREDENTIAL_HELPER"
GIT_CREDENTIALS_BASE64 = "GIT_CREDENTIALS_BASE64"
GITHUB_PERSONAL_ACCESS_TOKEN = "GITHUB_PERSONAL_ACCESS_TOKEN"
GH_TOKEN = "GH_TOKEN"

# --- GCP / Google Cloud ---
GCP_CREDENTIALS_BASE64_PREFIX = "GCP_CREDENTIALS_BASE64__"
GCP_ACTIVE_PROFILE = "GCP_ACTIVE_PROFILE"
GOOGLE_CLOUD_PROJECT = "GOOGLE_CLOUD_PROJECT"
GOOGLE_CLOUD_LOCATION = "GOOGLE_CLOUD_LOCATION"
GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
BIGQUERY_PROJECT = "BIGQUERY_PROJECT"
BIGQUERY_DATASETS = "BIGQUERY_DATASETS"
BIGQUERY_LOCATION = "BIGQUERY_LOCATION"
BIGQUERY_KEY_FILE = "BIGQUERY_KEY_FILE"


def gcp_credentials_key(profile: str) -> str:
    """プロファイル名からGCPクレデンシャルのキー名を生成する"""
    return f"{GCP_CREDENTIALS_BASE64_PREFIX}{profile}"


# --- Slack ---
SLACK_KEYS = ("SLACK_BOT_TOKEN", "SLACK_TEAM_ID",
              "SLACK_CHANNEL_ID", "SLACK_USER_MENTION")
